version: "3.9"

services:
    postgres:
        image: postgres:17.4
        container_name: monolith_authdb
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: monolith_authdb
            POSTGRES_USER: auth
            POSTGRES_PASSWORD: authpwd
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - auth_network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U auth -d monolith_authdb" ]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7.4
        container_name: jwt-redis
        ports:
            - "6379:6379"
        command: [ "redis-server", "--appendonly", "yes" ]

    adminer:
        image: adminer:latest
        container_name: auth_adminer
        restart: always
        ports:
            - "8888:8080"
        networks:
            - auth_network
        environment:
            ADMINER_DEFAULT_SERVER: postgres

volumes:
    postgres_data:

networks:
    auth_network:
        driver: bridge
