CREATE TABLE refresh_tokens
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    refresh_token VARCHAR(255)                            NOT NULL,
    expiry_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id       UUID                                    NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_refreshtoken UNIQUE (refresh_token);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
